### ISSUE TITLE
Missing py.typed file

### ISSUE THREAD

**Issue by FriedrichFroebel** [NCBM/fontra#5]
While the package appears to be typed, it is missing a `py.typed` file to indicate that it is indeed typed. This lets *mypy* fail:

```
brother_ql_web/font_helpers.py:63: error: Skipping analyzing "fontra": module is installed, but missing library stubs or py.typed marker  [import-untyped]
brother_ql_web/font_helpers.py:63: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

**Comment by NCBM** [comment]
I'll add it later.

There is something special for _mypy_. Since I uses _pylance_/_pyright_ with vscode, which can do type-checking without `py.typed` mark.

**Comment by FriedrichFroebel** [comment]
AFAIK this file will always be required if a package is distributed as a library and wants to indicate type hints according to PEP 561: https://peps.python.org/pep-0561/

**Comment by NCBM** [comment]
OK. Thanks for your information.

**Comment by NCBM** [comment]
In addition, I tested locally with _mypy_ and it reports that _fontTools_ package (an optional dependency) lacks typing (and it does). ~Since I'm unfamiliar with _mypy_, does it have effects on your project when checking with _mypy_?~

The stubs for _freetype-py_ (_fontra_'s dependency) is also a separate optional package. I tested without the stubs and it gave me errors. It does have an effect.

**Comment by FriedrichFroebel** [comment]
I have just verified that *mypy* now passes when using *fontra* in my code. 

*mypy* does not check recursively, id est *fontra* dependencies are irrelevant for any library users during type checking. Thus the *freetype-py* case is irrelevant here and *fontTools* is an optional dependency anyway, but would not have an effect on library usage as well.

**Comment by NCBM** [comment]
Thanks for your comment informing me it's OK, although separating CLI tools is a nice idea and maybe someday I would do it.
